SUPABASE_URL = "https://rvsoeplwykyvxkchdzjq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2c29lcGx3eWt5dnhrY2hkempxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1MTAxNTcsImV4cCI6MjA4MjA4NjE1N30.i3GwUNlzEuSsxiam4Ubnk-dAyf4-VoY_KqRpH2t4s_U"

